mutation(
        $firstName: String!
        $lastName: String!
        $email: String!
        $password: String!
        $profilePhoto: String!
        $age: String!
        $phoneNumber: String!
    ) {
        EmailSignUp(
            firstName: $firstName,
            lastName: $lastName,
            email: $email,
            password: $password,
            profilePhoto: $profilePhoto,
            age: $age
            phoneNumber: $phoneNumber
        ) {
            firstName,
            lastName
        }
    }